---
name: 'release'

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Release type [build, betafish, patch, minor, major]'
        required: true
        default: 'build'

jobs:
  release:
    name: release
    runs-on: ubuntu-20.04
    env:
      PACKAGECLOUD_TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6

      - name: install package_cloud
        run: gem install package_cloud

      - name: build package
        run: contrib/release-dokku ${{ github.event.inputs.release_type }}

      - name: upload packages
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build
